<?php

declare(strict_types=1);

namespace Luxid\Console\Commands;

use Luxid\Console\Command;

/**
 * Bridge command for Sentinel installation.
 *
 * This file is automatically generated and should not be edited.
 * It provides a bridge to the actual Sentinel install command.
 */
class SentinelInstallBridge extends Command
{
    protected string $description = 'Install Sentinel authentication package';

    public function handle(array $argv): int
    {
        // Check if Sentinel is installed and accessible
        if (!class_exists('\\Luxid\\Sentinel\\Registry')) {
            $this->error('Sentinel package not found or not properly installed.');
            $this->line('');
            $this->line('Make sure luxid/sentinel is installed:');
            $this->line('  composer require luxid/sentinel');
            return 1;
        }

        // Get the command from Sentinel's registry
        $command = \Luxid\Sentinel\Registry::getCommand('sentinel:install');

        if (!$command) {
            $this->error('Sentinel install command not registered.');
            $this->line('');
            $this->line('This may happen if:');
            $this->line('  1. Sentinel ServiceProvider was not registered');
            $this->line('  2. You need to run composer dump-autoload');
            return 1;
        }

        try {
            return $command->handle($argv);
        } catch (\Throwable $e) {
            $this->error('Failed to run install command: ' . $e->getMessage());
            return 1;
        }
    }
}
